version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 3000:3000
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/backend-challenge?createDatabaseIfNotExist=true
      - spring.datasource.username=amila_one
      - spring.datasource.password=Amila_pw
    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - .m2:/root/.m2

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: backend-challenge
      MYSQL_USER: amila_one
      MYSQL_PASSWORD: Amila_pw
      MYSQL_ROOT_PASSWORD: Amila_Rpw
    ports:
      - "3306:3306"
    networks:
      - springapimysql-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  springapimysql-net:
